<?php

function greetings_block_info(){
  return array(
	'greetings_block' => array(
	  'info' => t('Greetings block!!'),
  	),
  );
}

function greetings_block_view($delta=''){
  if (user_is_logged_in() == TRUE) {
    global $user;
    $block = array();
    if (date("H") < 12) {
      $block['content'] = t('Good Morning @uname..!', array('@uname' => $user->name));
	} 
	else if (date('H') > 11 && date("H") < 18) {
      $block['content'] = t('Good Afternoon @uname..!', array('@uname' => $user->name));
	} 
	else if(date('H') > 17) {
      $block['content'] = t('Good Evening @uname..!', array('@uname' => $user->name));
	}
  }
  else {
    $block['content'] = t('Welcome Anonymous');
   }
   return $block;
}