<?php

/**
 * @file
 * Adds a block that welcomes users when they log in.
 */

/**
 * Implements hook_menu().
 */
function greetings_menu() {
  $menus['admin/structure/greetings'] = array(
    'title' => 'Greeting message for Annonymous user',
    'page callback' => 'drupal_get_form',
    'access callback' => TRUE,
    'page arguments' => array('greetings_admin_settings'),
    'access arguments' => array('access administration pages'),
    'description' => 'Ajax callback for view loading.',
    'type' => MENU_NORMAL_ITEM,
  );
  return $menus;
}

/**
 * Implements callback in hook_menu().
 */
function greetings_admin_settings(){
  $form['greetings_alter_msg']=array(
    '#type' => 'textfield',
    '#title' => t('Alert message'),
    '#description' => t('Write a message to show to anonymous users'),
    '#default_value' => variable_get('greetings_alter_msg','Hello!'),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_block_info().
 */
function greetings_block_info() {
  return array(
	'greetings_block' => array(
	  'info' => t('Greetings block!!'),
  	),
  );
}

/**
 * Implements hook_block_view().
 */
function greetings_block_view() {
  if (user_is_logged_in() == TRUE) {
    global $user;
    $block = array();
    date_default_timezone_set('Asia/Calcutta');
    if (date("H") < 12) {
      $block['content'] = t('Good Morning @uname..!', array('@uname' => $user->name));
    } 
    elseif (date('H') > 11 && date("H") < 18) {
      $block['content'] = t('Good Afternoon @uname..!', array('@uname' => $user->name));
    } 
    elseif(date('H') > 17) {
      $block['content'] = t('Good Evening @uname..!', array('@uname' => $user->name));
    }
  }
  else {
    $block['content'] = variable_get('greetings_alter_msg','Hola!!');
   }
   return $block;
}

/**
 * Implements hook_help().
 */
function greetings_help($path, $arg) {
  switch ($path) {
    case '/admin/help#greetings':
      return '<p>' . t("This module will create one block named Greetings Block and it will show greetings according to current time") . '</p>';
      break;
  }
} 
